---
- name: "[preflight] - Set selinux to permissive"
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: "[preflight] - Disable swap"
  ansible.builtin.shell: |
    swapoff -a
  changed_when: false

- name: "[preflight] - Check for swap device"
  ansible.builtin.stat:
    path: /dev/zram0
  register: zram
  when: ansible_architecture == "aarch64"

- name: "[preflight] - Disable swap for raspi"
  ansible.builtin.shell: |
    swapoff /dev/zram0; zramctl --reset /dev/zram0
  when: zram.stat.exists

- name: "[preflight] - Check for zram-generator.conf"
  ansible.builtin.stat:
    path: /etc/systemd/zram-generator.conf
  register: p
  when: ansible_architecture == "aarch64"
  
- name: "[preflight] - Disable swap for raspi"
  ansible.builtin.file:
    path: /etc/systemd/zram-generator.conf
    state: present
    owner: root
    group: root
    mode: 0644
  when: p.stat.exists

- name: "[preflight] - Set the hostname"
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: "[preflight] - rhsm - Register to the CDN"
  community.general.redhat_subscription:
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    auto_attach: true
  when: ansible_distribution == "RedHat"

- name: "[preflight] - Install iproute-tc package"
  ansible.builtin.package:
    name: iproute-tc
    state: present

- name: "[preflight] - Load kernel modules"
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: "[preflight]- Load sysctl params"
  ansible.posix.sysctl:
    name: "{{ item }}"
    state: present
    reload: yes
    sysctl_set: yes
    value: '1'
  loop:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: "[preflight] - Install firewalld package"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - firewalld

- name: "[preflight] - Start and Enable firewalld service"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - firewalld

- name: "[preflight] - Configure firewalld"
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 10250-10252/tcp
    - 30000-32767/tcp
    - 6443/tcp
    - 2379-2380/tcp
    - 443/tcp
    - 80/tcp

- name: "[preflight] - Install python3-pip on controlplane"
  ansible.builtin.package:
    name: python3-pip
    state: present
  when: inventory_hostname in groups['controlplane']

- name: "[preflight] - Install kubernetes pip module"
  ansible.builtin.pip:
    name: kubernetes
    executable: pip3
  when: inventory_hostname in groups['controlplane']

